name = "CrimeAnalytics"
uuid = "c509c8b9-ba47-4fe5-8836-73e67328bd81"
authors = ["Samuel Yu <samuelyu@meta.com>"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
